eureka:
  client:
    # 服务器自身是否注册到eureka
    register-with-eureka: false
    # 是否同步节点
    fetch-registry: false
    # eureka页面url
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/
  instance:
    ip-address: localhost
    hostname: discovery-server

server:
  port: 8761

spring:
  application:
    name: discovery-server
