server:
  port: 8040
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # 配置git仓库的地址
          uri: "https://github.com/gbKidCoding/spring-cloud-example-discovery-eureka/"
          # git仓库地址下的相对地址，可以配置多个，用,分割
          search-paths: config-repo
